<?php

namespace Home\Controller;

/**
 * 前台标签控制器
 */
class CcguitarController extends BaseTaskController
{

    public $domain = "http://www.ccguitar.cn/";
    public $websitName = "虫虫吉他谱";
    public $lastData = array();
    public $detailLists = array();
    public $detailIdReg = "/[\\d]+/i";
    public $drawsoureId = 1;
    public $curentPageId = 1;
    public $pageUrlList = array(
        //吉他谱
        array('my_music_id' => 5, 'page' => 1, 'url' => 'pu_list_0_0_0_0_0_1.htm', 'format_url' => 'pu_list_0_0_0_0_0_{0}.htm', 'draw_page_count' =>10),
        //最新
        array('my_music_id' => 4, 'page' => 1, 'url' => 'wlgs_list.htm', 'format_url' => 'wlgs_list_0_{0}_0_0_0.htm', 'draw_page_count' => 10),
        //翻唱
        array('my_music_id' => 2, 'page' => 1, 'url' => 'wlgs_start_song.aspx?songtype=1', 'format_url' => 'wlgs_start_song.aspx?songtype=1&pageNo={0}', 'draw_page_count' => 10),
        //原创
        array('my_music_id' => 1, 'page' => 1, 'url' => 'wlgs_start_song.aspx?songtype=3', 'format_url' => 'wlgs_start_song.aspx?songtype=3&pageNo={0}', 'draw_page_count' => 10),
    );

    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->lastData = parent::getLastData();
    }

    public function index()
    {
        $this->getPageUrl();
        $this->saveDetail();
    }

    public function saveDetail()
    {
        parent::getList();
    }

    public function getUserId($str)
    {
        preg_match($this->detailIdReg, $str, $matchs);
        return $matchs[0] ? $matchs['0'] : '';
    }

    public function getUserName($str, $beginStr, $endStr)
    {
        $begin = strpos($str, $beginStr)+3;
        $end = strpos($str, $endStr);
        $length = $end - $begin;
        $name = substr($str, $begin, $length);
        return trim($name);
    }

    //原创
    public function getYuanChuanDetail($url,$type=1)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);

        //UCENTER_MEMBER
        $spans = pq('.pucenter')->children('span');
        $user = pq('.more:eq(2)')->attr('href');
        $artist_name = $this->getUserName($user, '给', '的');
        $username = $artist_name;
        $password = 'f3ff819109883d0e309965755349fe81';
        $email = pq($spans)->get(8)->html();;
        $reg_time = NOW_TIME;
        $status = 1;
        //song
        $title = pq('title');
        $name = pq($title)->html();
        $name = substr($name, 0, strpos($name, ' '));
        $genre_id = $type;
        $genre_name = $this->getType(1);
        $album_id = 0;
        $album_name = '';
        $order_id = 0;
        $href = pq('.more:eq(0)')->attr('href');
        $artist_id = $this->getUserId($href);

        $tags = '';
        $cover_id = 0;
        $imgurl = pq('#tsstr')->find('img')->attr('src');
        $cover_url = parent::getUploadPath($imgurl, 'Picture');
        $up_uid = $artist_id;
        $up_uname = $artist_name;
        $diHtml = pq('#un1num')->html();
        $digg = $this->getUserId($diHtml);
        $caiHtml = pq('#un-1num')->html();
        $bury = $this->getUserId($caiHtml);
        $server_id = 0;
        $mix = '';
        $download = 0;
        $hits = pq('hits')->html();
        $rater = $this->getUserName($hits, '(', '票)');
        $listens = $this->getUserName($hits, '点击：', '  网评');
        $recommend = 0;
        $sing = $genre_name;
        $position = 0;
        $favtimes = 0;
        $likes = 0;
        $score = 0;
        $coin = 0;
        $comment = 100;
        $song = pq('.tabs:eq(1)')->next()->html();
        $lyrics = $this->getUserName($song, '词：', "<br>");
        $composer = $this->getUserName($song, '曲：', "<br>");
        $midi = $this->getUserName($song, '编曲：', "<br>");
        $add_time = NOW_TIME;
        $update_time = NOW_TIME;
        $staus = 1;

        //songs_extend
        $src = pq('audio:eq(0)')->attr('src');
        $listen_url = parent::getUploadPath($imgurl, 'Music');
        $down_url = $listen_url;
        $listen_file_id = 0;
        $down_file_id = 0;
        $file_size = 0;
        $play_time = 0;
        $bitrate = 0;
        $disk_url = '';
        $disk_pass = '';
        $down_rule = '';
        $lrc = $song;
        $introduce = '';

        //member


        $avatarPath = pq('.xspace-signavatar:eq(0)')->attr('src');
        $avatarOss = parent::getUploadPath($avatarPath, 'Avatar');
        $pic_id = parent::addPicture($avatarOss);
        $qq = pq($spans)->get(6)->html();
        $signature = '';
        $nickname = $artist_name;
        $location = '';
        $province = 0;
        $city = 0;
        $district = 0;
        $space = 0;
        $mobile = '';
        $member = array(
            'nickname' => $artist_name,
            'pic_id' => $pic_id,
            'hits' => $hits,
            'qq' => $qq,
            'signature' => '',
            'location' => '',
            'space' => 0,
            'cdkey' => ''

        );
        $uid=parent::addMember($member);
        $song=array(
            'name'=>$name,
            'genre_id'=>$genre_id,
            'genre_name'=>$genre_name,
            'album_id'=>$album_id,
            'genre_name'=>$genre_name,
            'artist_id'=>$uid,
            'artist_name'=>$artist_name,
            'tags'=>'',
            'cover_id'=>$cover_id,
            'cover_url'=>$cover_url,
            'up_uid'=>$uid,
            'up_uname'=>$artist_name,
            'digg'=>$digg,
            'bury'=>$bury,
            'server_id'=>0,
            'mix'=>'',
            'rater'=>$rater,
            'listens'=>$listens,
            'sing'=>$sing,
            'comment'=>$comment,
            'lyrics'=>$lyrics,
            'composer'=>$composer,
            'midi'=>$midi,
            'add_time'=>$add_time,
            'update_time'=>$update_time,
            'status'=>1
        );
        $songId=parent::addSong($song);
        $songs_extend=array(
            'mid'=>$songId,
            'listen_url'=>$listen_url,
            'down_url'=>$listen_url,
            'play_time'=>0,
            'disk_url'=>'',
            'disk_pass'=>'',
            'down_rule'=>'',
            'lrc'=>$lrc,
            'introduce'=>''
        );
        $songsExtendId=parent::addSongExtend($songs_extend);
        $ucenterMember=array(
            'username'=>$username,
            'password'=>$password,
            'email'=>$email,
            'mobile'=>'18305954587',
            'reg_time'=>NOW_TIME,
            'reg_ip'=>'',
            'last_login_time'=>NOW_TIME,
            'last_login_ip'=>'',
            'update_time'=>NOW_TIME,
            'status'=>1,

        );
        parent::addUcenterMember($ucenterMember);
        $pictureData['id']=$pic_id;
        $pictureData['uid']=$uid;
        parent::updatePicture($pictureData);

    }

    //翻唱
    public function getLikeDetail($url,$type)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);

        //UCENTER_MEMBER
        $spans = pq('.pucenter')->children('span');
        $user = pq('.more:eq(2)')->attr('href');
        $artist_name = $this->getUserName($user, '给', '的');
        $username = $artist_name;
        $password = 'f3ff819109883d0e309965755349fe81';
        $email = pq($spans)->get(8)->html();;
        $reg_time = NOW_TIME;
        $status = 1;
        //song
        $title = pq('title');
        $name = pq($title)->html();
        $name = substr($name, 0, strpos($name, ' '));
        $genre_id = $type;
        $genre_name = $this->getType(1);
        $album_id = 0;
        $album_name = '';
        $order_id = 0;
        $href = pq('.more:eq(0)')->attr('href');
        $artist_id = $this->getUserId($href);

        $tags = '';
        $cover_id = 0;
        $imgurl = pq('#tsstr')->find('img')->attr('src');
        $cover_url = parent::getUploadPath($imgurl, 'Picture');
        $up_uid = $artist_id;
        $up_uname = $artist_name;
        $diHtml = pq('#un1num')->html();
        $digg = $this->getUserId($diHtml);
        $caiHtml = pq('#un-1num')->html();
        $bury = $this->getUserId($caiHtml);
        $server_id = 0;
        $mix = '';
        $download = 0;
        $hits = pq('hits')->html();
        $rater = $this->getUserName($hits, '(', '票)');
        $listens = $this->getUserName($hits, '点击：', '  网评');
        $recommend = 0;
        $sing = $genre_name;
        $position = 0;
        $favtimes = 0;
        $likes = 0;
        $score = 0;
        $coin = 0;
        $comment = 100;
        $song = pq('.tabs:eq(1)')->next()->html();
        $lyrics = $this->getUserName($song, '词：', "<br>");
        $composer = $this->getUserName($song, '曲：', "<br>");
        $midi = $this->getUserName($song, '编曲：', "<br>");
        $add_time = NOW_TIME;
        $update_time = NOW_TIME;
        $staus = 1;

        //songs_extend
        $src = pq('audio:eq(0)')->attr('src');
        $listen_url = parent::getUploadPath($imgurl, 'Music');
        $down_url = $listen_url;
        $listen_file_id = 0;
        $down_file_id = 0;
        $file_size = 0;
        $play_time = 0;
        $bitrate = 0;
        $disk_url = '';
        $disk_pass = '';
        $down_rule = '';
        $lrc = $song;
        $introduce = '';

        //member


        $avatarPath = pq('.xspace-signavatar:eq(0)')->attr('src');
        $avatarOss = parent::getUploadPath($avatarPath, 'Avatar');
        $pic_id = parent::addPicture($avatarOss);
        $qq = pq($spans)->get(6)->html();
        $signature = '';
        $nickname = $artist_name;
        $location = '';
        $province = 0;
        $city = 0;
        $district = 0;
        $space = 0;
        $mobile = '';
        $member = array(
            'nickname' => $artist_name,
            'pic_id' => $pic_id,
            'hits' => $hits,
            'qq' => $qq,
            'signature' => '',
            'location' => '',
            'space' => 0,
            'cdkey' => ''

        );
        $uid=parent::addMember($member);
        $song=array(
            'name'=>$name,
            'genre_id'=>$genre_id,
            'genre_name'=>$genre_name,
            'album_id'=>$album_id,
            'genre_name'=>$genre_name,
            'artist_id'=>$uid,
            'artist_name'=>$artist_name,
            'tags'=>'',
            'cover_id'=>$cover_id,
            'cover_url'=>$cover_url,
            'up_uid'=>$uid,
            'up_uname'=>$artist_name,
            'digg'=>$digg,
            'bury'=>$bury,
            'server_id'=>0,
            'mix'=>'',
            'rater'=>$rater,
            'listens'=>$listens,
            'sing'=>$sing,
            'comment'=>$comment,
            'lyrics'=>$lyrics,
            'composer'=>$composer,
            'midi'=>$midi,
            'add_time'=>$add_time,
            'update_time'=>$update_time,
            'status'=>1
        );
        $songId=parent::addSong($song);
        $songs_extend=array(
            'mid'=>$songId,
            'listen_url'=>$listen_url,
            'down_url'=>$listen_url,
            'play_time'=>0,
            'disk_url'=>'',
            'disk_pass'=>'',
            'down_rule'=>'',
            'lrc'=>$lrc,
            'introduce'=>''
        );
        $songsExtendId=parent::addSongExtend($songs_extend);
        $ucenterMember=array(
            'username'=>$username,
            'password'=>$password,
            'email'=>$email,
            'mobile'=>'18305954587',
            'reg_time'=>NOW_TIME,
            'reg_ip'=>'',
            'last_login_time'=>NOW_TIME,
            'last_login_ip'=>'',
            'update_time'=>NOW_TIME,
            'status'=>1,

        );
        parent::addUcenterMember($ucenterMember);
        $pictureData['id']=$pic_id;
        $pictureData['uid']=$uid;
        parent::updatePicture($pictureData);
    }

    //最新
    public function getNewDetail($url,$type)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);

        //UCENTER_MEMBER
        $spans = pq('.pucenter')->children('span');
        $user = pq('.more:eq(2)')->attr('href');
        $artist_name = $this->getUserName($user, '给', '的');
        $username = $artist_name;
        $password = 'f3ff819109883d0e309965755349fe81';
        $email = pq($spans)->get(8)->html();;
        $reg_time = NOW_TIME;
        $status = 1;
        //song
        $title = pq('title');
        $name = pq($title)->html();
        $name = substr($name, 0, strpos($name, ' '));
        $genre_id = $type;
        $genre_name = $this->getType(1);
        $album_id = 0;
        $album_name = '';
        $order_id = 0;
        $href = pq('.more:eq(0)')->attr('href');
        $artist_id = $this->getUserId($href);

        $tags = '';
        $cover_id = 0;
        $imgurl = pq('#tsstr')->find('img')->attr('src');
        $cover_url = parent::getUploadPath($imgurl, 'Picture');
        $up_uid = $artist_id;
        $up_uname = $artist_name;
        $diHtml = pq('#un1num')->html();
        $digg = $this->getUserId($diHtml);
        $caiHtml = pq('#un-1num')->html();
        $bury = $this->getUserId($caiHtml);
        $server_id = 0;
        $mix = '';
        $download = 0;
        $hits = pq('hits')->html();
        $rater = $this->getUserName($hits, '(', '票)');
        $listens = $this->getUserName($hits, '点击：', '  网评');
        $recommend = 0;
        $sing = $genre_name;
        $position = 0;
        $favtimes = 0;
        $likes = 0;
        $score = 0;
        $coin = 0;
        $comment = 100;
        $song = pq('.tabs:eq(1)')->next()->html();
        $lyrics = $this->getUserName($song, '词：', "<br>");
        $composer = $this->getUserName($song, '曲：', "<br>");
        $midi = $this->getUserName($song, '编曲：', "<br>");
        $add_time = NOW_TIME;
        $update_time = NOW_TIME;
        $staus = 1;

        //songs_extend
        $src = pq('audio:eq(0)')->attr('src');
        $listen_url = parent::getUploadPath($imgurl, 'Music');
        $down_url = $listen_url;
        $listen_file_id = 0;
        $down_file_id = 0;
        $file_size = 0;
        $play_time = 0;
        $bitrate = 0;
        $disk_url = '';
        $disk_pass = '';
        $down_rule = '';
        $lrc = $song;
        $introduce = '';

        //member


        $avatarPath = pq('.xspace-signavatar:eq(0)')->attr('src');
        $avatarOss = parent::getUploadPath($avatarPath, 'Avatar');
        $pic_id = parent::addPicture($avatarOss);
        $qq = pq($spans)->get(6)->html();
        $signature = '';
        $nickname = $artist_name;
        $location = '';
        $province = 0;
        $city = 0;
        $district = 0;
        $space = 0;
        $mobile = '';
        $member = array(
            'nickname' => $artist_name,
            'pic_id' => $pic_id,
            'hits' => $hits,
            'qq' => $qq,
            'signature' => '',
            'location' => '',
            'space' => 0,
            'cdkey' => ''

        );
        $uid=parent::addMember($member);
        $song=array(
            'name'=>$name,
            'genre_id'=>$genre_id,
            'genre_name'=>$genre_name,
            'album_id'=>$album_id,
            'genre_name'=>$genre_name,
            'artist_id'=>$uid,
            'artist_name'=>$artist_name,
            'tags'=>'',
            'cover_id'=>$cover_id,
            'cover_url'=>$cover_url,
            'up_uid'=>$uid,
            'up_uname'=>$artist_name,
            'digg'=>$digg,
            'bury'=>$bury,
            'server_id'=>0,
            'mix'=>'',
            'rater'=>$rater,
            'listens'=>$listens,
            'sing'=>$sing,
            'comment'=>$comment,
            'lyrics'=>$lyrics,
            'composer'=>$composer,
            'midi'=>$midi,
            'add_time'=>$add_time,
            'update_time'=>$update_time,
            'status'=>1
        );
        $songId=parent::addSong($song);
        $songs_extend=array(
            'mid'=>$songId,
            'listen_url'=>$listen_url,
            'down_url'=>$listen_url,
            'play_time'=>0,
            'disk_url'=>'',
            'disk_pass'=>'',
            'down_rule'=>'',
            'lrc'=>$lrc,
            'introduce'=>''
        );
        $songsExtendId=parent::addSongExtend($songs_extend);
        $ucenterMember=array(
            'username'=>$username,
            'password'=>$password,
            'email'=>$email,
            'mobile'=>'18305954587',
            'reg_time'=>NOW_TIME,
            'reg_ip'=>'',
            'last_login_time'=>NOW_TIME,
            'last_login_ip'=>'',
            'update_time'=>NOW_TIME,
            'status'=>1,

        );
        parent::addUcenterMember($ucenterMember);
        $pictureData['id']=$pic_id;
        $pictureData['uid']=$uid;
        parent::updatePicture($pictureData);
    }

    //吉他谱
    public function getGuitarDetail($url,$type)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);
        //UCENTER_MEMBER
        $user=pq('.more:eq(2)')->html();
        $user= iconv('gb2312','utf-8',$user);
        $artist_name = $this->getUserName($user, '给', '留言');

        $username = $artist_name;
        $password = 'f3ff819109883d0e309965755349fe81';
        $spans = pq('.pucenter:eq(0) span:eq(7)');
        $email=pq($spans)->html();
        $email= iconv('gb2312','utf-8',$email);
        $reg_time = NOW_TIME;
        $status = 1;
        //song
        $title = pq('title');
        $name = pq($title)->html();
        $name = substr($name, 0, strpos($name, ' '));

        $name= iconv('gb2312','utf-8',$name);

        $genre_id = $type;
        $genre_name = $this->getType(1);
        $album_id = 0;
        $album_name = '';
        $order_id = 0;
        $href = pq('.more:eq(0)')->attr('href');
        $artist_id = $this->getUserId($href);
        $tags = '';
        $cover_id = 0;
            $imgurl = pq('.xspace-signavatar:eq(0)')->attr('src');
        $cover_url = parent::getUploadPath($imgurl, 'Avatars');
        $up_uid = $artist_id;
        $up_uname = $artist_name;
        $diHtml = pq('#un1num')->html();
        $digg = $this->getUserId($diHtml);
        $caiHtml = pq('#un-1num')->html();
        $bury = $this->getUserId($caiHtml);
        $server_id = 0;
        $mix = '';
        $download = 0;
        $hits = pq('hits')->html();
        $rater = $this->getUserName($hits, '(', '票)');
        $listens = $this->getUserName($hits, '点击：', '  网评');
        $recommend = 0;
        $sing = $genre_name;
        $position = 0;
        $favtimes = 0;
        $likes = 0;
        $score = 0;
        $coin = 0;
        $comment = 100;
        $song = pq('.tabs:eq(1)')->next()->html();
     //   $lyrics = $this->getUserName($song, '词：', "<br>");
        $lyrics=$username;
     //   $composer = $this->getUserName($song, '曲：', "<br>");
        $composer=$username;
       // $midi = $this->getUserName($song, '编曲：', "<br>");
        $midi=$username;
        $add_time = NOW_TIME;
        $update_time = NOW_TIME;
        $staus = 1;

        //songs_extend
        $src = pq('audio:eq(0)')->attr('src');
        if($src){
            $listen_url = parent::getUploadPath($src, 'Music');
        }else{
            $listen_url='';
        }
        $jitapu=pq('.swiper-slide');
        $jitapuArr=array();
        foreach($jitapu as $val){
            $onesrc= pq($val)->find('img')->attr('src');
            array_push($jitapuArr,$onesrc);
        }
        $introducesList=array();
       foreach($jitapuArr as $val){
            $jipu=trim($val);
           $jitapuOss=parent::getUploadPath($jipu,'Music');
           array_push($introducesList,$jitapuOss);
       }
        $introduce='';
        foreach($introducesList as $val){
            $introduce.=format('<img src="{0}" alt="" /><br />',$val['path']);
        }
        $down_url = $listen_url;
        $listen_file_id = 0;
        $down_file_id = 0;
        $file_size = 0;
        $play_time = 0;
        $bitrate = 0;
        $disk_url = '';
        $disk_pass = '';
        $down_rule = '';
        $lrc = $song;
        $introduce = $introduce;

        //member


        $avatarPath = pq('.xspace-signavatar:eq(0)')->attr('src');

        $avatarOss = parent::getUploadPath($avatarPath, 'Avatar');
        $pic_id = parent::addPicture($avatarOss);
        $qq = '';
        $signature = '';
        $nickname = $artist_name;
        $location = '';
        $province = 0;
        $city = 0;
        $district = 0;
        $space = 0;
        $mobile = '';
        $member = array(
            'nickname' => $artist_name,
            'pic_id' => $pic_id,
            'hits' => $hits,
            'qq' => $qq,
            'signature' => '',
            'location' => '',
            'space' => 0,
            'cdkey' => ''

        );
        $uid=parent::addMember($member);

        $song=array(
            'name'=>$name,
            'genre_id'=>$genre_id,
            'genre_name'=>$genre_name,
            'album_id'=>$album_id,
            'genre_name'=>$genre_name,
            'artist_id'=>$uid,
            'artist_name'=>$artist_name,
            'tags'=>'',
            'cover_id'=>$cover_id,
            'cover_url'=>$cover_url,
            'up_uid'=>$uid,
            'up_uname'=>$artist_name,
            'digg'=>$digg,
            'bury'=>$bury,
            'server_id'=>0,
            'mix'=>'',
            'rater'=>$rater,
            'listens'=>$listens,
            'sing'=>$sing,
            'comment'=>$comment,
            'lyrics'=>$lyrics,
            'composer'=>$composer,
            'midi'=>$midi,
            'add_time'=>$add_time,
            'update_time'=>$update_time,
            'status'=>1
        );


        $songId=parent::addSong($song);
        $songs_extend=array(
            'mid'=>$songId,
            'listen_url'=>$listen_url,
            'down_url'=>$listen_url,
            'play_time'=>0,
            'disk_url'=>'',
            'disk_pass'=>'',
            'down_rule'=>'',
            'lrc'=>'',
            'introduce'=>$introduce
        );
        $songsExtendId=parent::addSongExtend($songs_extend);

        $ucenterMember=array(
            'username'=>$username,
            'password'=>$password,
            'email'=>$email,
            'mobile'=>'18305954587',
            'reg_time'=>NOW_TIME,
            'reg_ip'=>'1520509301',
            'last_login_time'=>NOW_TIME,
            'last_login_ip'=>'1520509301',
            'update_time'=>NOW_TIME,
            'status'=>1,

        );
        parent::addUcenterMember($ucenterMember);
        $pictureData['id']=$pic_id;
        $pictureData['uid']=$uid;
        parent::updatePicture($pictureData);
        echo 'success';exit;

    }

    public function getOne($detail, $type)
    {
        $one = array();
        $getUrl = format('{0}{1}', $detail['domain'], $detail['detail_url']);
        switch ($type) {
            case 1:
                $one = $this->getYuanChuanDetail($getUrl,1);
                break;
            case 2:
                $one = $this->getLikeDetail($getUrl,2);
                break;
            case 4:
                $one = $this->getNewDetail($getUrl,4);
                break;
            case 5:
                $one = $this->getGuitarDetail($getUrl,5);
                break;
            default:
                break;
        }
        return $one;
    }

    public function getDetailId($url)
    {
        preg_match($this->detailIdReg, $url, $matches);
        return $matches[0];
    }

    public function getNew($url)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);
        $pImags = pq('.p_img');
        $this->detailLists = array();
        foreach (pq($pImags) as $img) {
            $detailUrl = pq($img)->find('a')->attr('href');
            parent::pushDetail($detailUrl, 4);
        }
    }

    public function getLike($url)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);
        $pImags = pq('.xspace-signavatar');
        foreach (pq($pImags) as $val) {
            $a = pq($val)->next();
            $detailUrl = pq($a)->attr('href');
            parent::pushDetail($detailUrl, 2);
        }
    }

    public function origin($url)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);
        $pImags = pq('.xspace-signavatar');
        foreach (pq($pImags) as $val) {
            $a = pq($val)->next();
            $detailUrl = pq($a)->attr('href');
            parent::pushDetail($detailUrl, 1);
        }
    }

    //吉他谱
    public function gutarpu($url)
    {
        require_once(VENDOR_PATH . "phpQuery/phpQuery.php");
        header("Content-type: text/html; charset=utf-8");
        $pageHtml = \phpQuery::newDocumentFile($url);
        $as = pq('.imagewall_container a');
        foreach (pq($as) as $val) {
            $detailUrl = pq($val)->attr('href');
            parent::pushDetail($detailUrl, 5);
        }
    }

    public function urlTODetailLinks($url, $type)
    {
        switch ($type) {
            //最新
            case 4:
                $this->getNew($url);
                break;
            //翻唱
            case 2:
                $this->getLike($url);
                break;
            //原创
            case 1:
                $this->origin($url);
                break;
            //吉他谱
            case 5:
                $this->gutarpu($url);
                break;
            default:
                break;
        }


    }


}